<a href="https://colab.research.google.com/github/sakshidabral/NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data preprocessing, csv files i/o

**Step 1 : TEXT PREPROCESSING**



LOWERCASING

In [ ]:
sent1='Today Is A NIce Day'
sent1.lower()

'today is a nice day'

In [ ]:
# for csv file data set
# df=pd.read('sample.csv')
# df['column_name'] = df['column_name'].str.lower()

REMOVE HTML TAGS

In [ ]:
import re
def remove_html_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)

In [ ]:
text='< p > HEllow WORLD <br> < /p> '
remove_html_tags(text)

' HEllow WORLD   '

REMOVE URLS

In [ ]:
import re
def remove_url(text):
  pattern=re.compile(r'https?://\S+|www.\.\S+')
  return pattern.sub(r'',text)

In [ ]:
text='google search e'

'google search engine : '

REMOVE PUNCTUATIONS

CHAT WORD TREATMENT

SPELLING CORRECTION

REMOVING STOP WORDS

HANDING EMOJIS

TOKENIZATION



1. Using the split function

In [ ]:
# word tokenization
sent1='I am going to Delhi.'
sent1.split()

['I', 'am', 'going', 'to', 'Delhi.']

In [ ]:
# sentence tokenization
sent2='I am studying. It is very difficult. I am doing DSA.'
sent2.split('.')

['I am studying', ' It is very difficult', ' I am doing DSA', '']

In [ ]:
# problem faced in using split function
sent3='Since when are you here? Never saw you'  # does not split at ?
sent3.split('.')

['Since when are you here? Never saw you']

2. Regular Expression

In [ ]:
import re
sent4='I am going to Delhi!'
tokens=re.findall("[\w']+",sent4)
tokens

['I', 'am', 'going', 'to', 'Delhi']

3. NLTK

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize,sent_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
sent1='i am going to delhi!'
word_tokenize(sent1)

['i', 'am', 'going', 'to', 'delhi', '!']

4. Spacy

In [ ]:
import spacy
nlp=spacy.load('en_core_web_sm') # load english small dictionary

In [ ]:
sent5='I have a Ph.D in A.I.'
sent6="We're here to help! Mail us at abc@gmail.com"
# convert sent into document
doc1=nlp(sent5)
doc2=nlp(sent6)

In [ ]:
for token in doc2:
  print(token)

We
're
here
to
help
!
Mail
us
at
abc@gmail.com


STEMMING

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps=PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
sample='walk walking walked walks'
stem_words(sample)

'walk walk walk walk'

LEMMATIZATION

---


*   Stemming uses an algorithm to find what the root word shoud be. It is not neccessary that the root word after stemming is actually present in our language.
*   Lemmatization uses searching approach in lexicographical order.
*   Stemming is faster than lemmatization
* Use lemmatization only when root words are to be shown to user on screen







**Step 2 : FEATURE EXTRACTION**

1) BAG OF WORDS

In [2]:
import numpy as np
import pandas as pd
df=pd.DataFrame({'text':['people watch campus','campus watch campus','people write comment','campus write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch campus       1
1   campus watch campus       1
2  people write comment       0
3  campus write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campus': 0, 'write': 4, 'comment': 1}


In [7]:
for i in range(4) :
  print(bow[i].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


2) N-GRAMS

In [8]:
# bi-grams
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))
bow=cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people watch': 2, 'watch campus': 4, 'campus watch': 0, 'people write': 3, 'write comment': 5, 'campus write': 1}


In [9]:
for i in range(4) :
  print(bow[i].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


3) TF-IDF

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [12]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campus' 'comment' 'people' 'watch' 'write']
